services:
    _defaults:
        autowire: true
        autoconfigure: true

    AlexanderA2\SymfonyBasics\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Tests/'

    AlexanderA2\SymfonyBasics\Translation\Translator:
        decorates: translator